"""LLM-as-judge: is the generated answer compliant with the repository?

The judge receives **every** validated wording of a question, up to a
cap. The question put to it makes that plurality explicit: the answer
must be equivalent to at least one wording and contradict none.

The prompt itself stays in French, like the content it judges.
"""

import json
import re
from typing import Protocol, runtime_checkable

from loguru import logger

from .matching import lexical_similarity
from .schemas import Verdict

JUDGE_SYSTEM_PROMPT = """Tu arbitres la conformité d'une réponse produite
par un système de questions-réponses d'assurance.

On te donne une question, une réponse candidate, et une liste de
formulations déjà validées par le métier pour cette même question. Ces
formulations sont toutes correctes : elles disent la même chose de
manières différentes.

La réponse candidate est conforme si, et seulement si, elle est
équivalente sur le fond à **au moins une** des formulations validées et
qu'elle n'en contredit **aucune**. Une différence de style, de longueur ou
de mise en forme n'est pas une non-conformité. Un chiffre, un délai, une
condition ou une exclusion qui diffère en est une.

Réponds uniquement par un objet JSON :
{"conforme": true|false, "confiance": 0.0-1.0, "motif": "une phrase"}"""


@runtime_checkable
class AnswerJudge(Protocol):
    """Judges the compliance of a candidate answer."""

    def judge(
        self,
        question: str,
        candidate_answer: str,
        validated_answers: list[str],
    ) -> Verdict:
        """Return a verdict.

        Args:
            question: Question asked.
            candidate_answer: Answer generated by the RAG.
            validated_answers: Wordings validated by the business team.

        Returns:
            The verdict.
        """
        ...


class LexicalJudge:
    """Deterministic offline judge, based on vocabulary overlap.

    It makes no semantic claim: it exists so that the demonstration and
    the tests run without an API key or network access.
    """

    def __init__(self, threshold: float = 0.6) -> None:
        """Initialize the judge.

        Args:
            threshold: Minimum overlap with one of the validated wordings
                required to declare compliance.
        """
        self.threshold = threshold

    def judge(
        self,
        question: str,
        candidate_answer: str,
        validated_answers: list[str],
    ) -> Verdict:
        """Return a verdict from the maximum vocabulary overlap.

        Args:
            question: Question asked (unused, kept for the protocol).
            candidate_answer: Answer generated by the RAG.
            validated_answers: Wordings validated by the business team.

        Returns:
            The verdict.
        """
        del question
        if not validated_answers:
            return Verdict(
                conforme=False,
                confiance=0.0,
                motif="Aucune formulation validée pour comparer.",
            )
        best = max(
            lexical_similarity(candidate_answer, reference)
            for reference in validated_answers
        )
        return Verdict(
            conforme=best >= self.threshold,
            confiance=round(min(1.0, best), 4),
            motif=(
                f"Recouvrement lexical maximal de {best:.2f} avec les "
                f"formulations validées (seuil {self.threshold:.2f})."
            ),
        )


class ClaudeJudge:
    """Judge backed by the Claude API."""

    def __init__(
        self,
        client: object,
        model: str = "claude-sonnet-5",
        max_references: int = 5,
    ) -> None:
        """Initialize the judge.

        Args:
            client: Configured `anthropic.Anthropic` client.
            model: Model identifier.
            max_references: Maximum number of wordings sent to the judge,
                to cap the prompt size.
        """
        self._client = client
        self.model = model
        self.max_references = max_references

    def judge(
        self,
        question: str,
        candidate_answer: str,
        validated_answers: list[str],
    ) -> Verdict:
        """Return a verdict by querying Claude.

        Args:
            question: Question asked.
            candidate_answer: Answer generated by the RAG.
            validated_answers: Wordings validated by the business team.

        Returns:
            The verdict. An unreadable reply yields a non-compliant
            verdict with zero confidence, which sends the case to review.
        """
        references = validated_answers[: self.max_references]
        wordings = "\n".join(
            f"{index}. {text}"
            for index, text in enumerate(references, start=1)
        )
        message = (
            f"Question :\n{question}\n\n"
            f"Formulations validées :\n{wordings or '(aucune)'}\n\n"
            f"Réponse candidate :\n{candidate_answer}"
        )
        response = self._client.messages.create(
            model=self.model,
            max_tokens=1024,
            system=JUDGE_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": message}],
        )
        text = "".join(
            block.text for block in response.content if block.type == "text"
        )
        return _parse_verdict(text)


def _parse_verdict(text: str) -> Verdict:
    """Extract a verdict from a model reply.

    Args:
        text: Raw reply of the model.

    Returns:
        The verdict, or a non-compliant verdict with zero confidence when
        the reply cannot be used — the case then goes to review.
    """
    found = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if found:
        try:
            payload = json.loads(found.group(0))
            return Verdict(
                conforme=bool(payload["conforme"]),
                confiance=float(payload.get("confiance", 0.5)),
                motif=str(payload.get("motif", "")),
            )
        except (ValueError, KeyError, TypeError) as error:
            logger.warning("Verdict illisible : {}", error)
    return Verdict(
        conforme=False,
        confiance=0.0,
        motif="Verdict du juge illisible : cas envoyé en revue.",
    )
